# Generated by Django 6.0.1 on 2026-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('JP', 'Japan'), ('IN', 'India'), ('CN', 'China'), ('BR', 'Brazil'), ('CA', 'Canada')], max_length=2, null=True)),
            ],
        ),
    ]
